---
title: "Package Usage"
author: "Alex Gold"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  ---
  
  ```{r setup, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```

```{r}
library(magrittr)
pdf_text <- here::here("data", "USSC_Public_Release_Codebook_FY99_FY16.pdf")
pdf <- pdf_load(pdf_text, pages = seq(7, 57), 
                drop_from_top = 1, drop_from_bottom = 1)

pdf %>% 
  suggest_cols()
```

```{r}
# Edit cols
l[[2]] %<>% remove_cols(4)
l[[3]] %<>% remove_cols(4)
l[[7]] %<>% remove_cols(4)
l[[10]] %<>% remove_cols(4)
l[[11]] %<>% remove_cols(4)
l[[23]] %<>% remove_cols(4)
l[[24]] %<>% remove_cols(4, verbose = F) %>% suggest_rows()
l[[29]] %<>% remove_cols(4)
l[[32]] %<>% remove_cols(4:5, verbose = F) %>% suggest_rows()
l[[51]] %<>% remove_cols(4)
purrr::map(l, function(l) if(length(l$cols) > 4) l) %>% purrr::discard(is.null)

# Change to df
l <- purrr::map(l, tab_text_to_df)
```
